destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/cwn-pdf"
port: 4011
output: pdf
product: cwn
print_title: Codewarz Player's Guide
print_subtitle: version 1.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true